### ISSUE TITLE
Installation Query 

### ISSUE THREAD

**Issue by ghost** [jonahar/lightning-systemic-attack#1]
Hi

I am trying to setup the environment for running the simulations and I have a question about the install process.

Is it assumed we must install all the components of the bin folder ourselves or is there a script I have missed a script does this for us?

What would be the ideal order of scripts (if any) to get simulations up and running?

Many Thanks.

**Comment by jonahar** [comment]
Yes, as the README says, you should set up the bin folder with the appropriate executables.
If you have all the different implementations on your machine, you could do something like
```
cd lightning-systemic-attack/bin
ln -s /path/to/bitcoin-cli bitcoin-cli
ln -s /path/to/bitcoind bitcoind
ln -s /path/to/eclair-cli eclair-cli
ln -s /path/to/eclair-node eclair-node
ln -s /path/to/lightning-cli lightning-cli
ln -s /path/to/lightningd lightningd
ln -s /path/to/lightningd-evil lightningd-evil
ln -s /path/to/lncli lncli
ln -s /path/to/lnd lnd
```
Note that `lightningd-evil` is an attacker's node implementation that we did not release.


When you're done with that, all you need is a simulation script, that can be generated using either the `commands_generator` module directly or the `generate_attack_simulation_scripts.py` python script.

**Comment by ghost** [comment]
Thank you for the clarification!
